services:
- docker

git:
  submodules: false

before_script:
- docker-compose up -d
- docker stats --no-stream
- docker-compose exec g3w-suite sh -c "wait-for-it -h localhost -p 8000 -t 180"

script:
- docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python manage.py test core"
- docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python manage.py test qdjango"

after_script:
- docker-compose down