version: '3'
services:
  postgis:
    image: kartoza/postgis:11.0-2.5
    ports:
    - "55432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DBNAME: g3w-suite
    volumes:
      - shared-volume:/shared-volume

  qgisserver:
    image: kartoza/qgis-server:LTR
    ports:
    - "8001:80"
    volumes:
      - shared-volume:/shared-volume

  g3w-suite:
    build: .
    command: "/code/entrypoint_docker.sh"
    ports:
    - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - postgis
    volumes:
      - shared-volume:/shared-volume

volumes:
    shared-volume: